PyArray_{Object → MinScalar}Type
Since numpy 1.6 (14 May 2011), PyArray_ObjectType is superseded by
PyArray_MinScalarType and/or PyArray_ResultType.

In numpy 1.20, EIGENPY_GET_PY_ARRAY_TYPE stopped returning the expected
type_num for user defined types, and returned NPY_OBJECT instead.

The py-user-type unit test was failing with:

Traceback (most recent call last):
  File "…/eigenpy/unittest/python/test_user_type.py", line 27, in <module>
    mat = user_type.create_double(rows,cols)
RuntimeError: You asked for a conversion which is not implemented.